copyright: Copyright &copy; 2021 - 2022 Lento Manickathan

edit_uri: edit/main/docs/

repo_name: lento234/lento234.github.io
repo_url: https://github.com/lento234/lento234.github.io

site_author: Lento Manickathan
site_description: Lento Manickathan's personal website
site_dir: public
site_name: Lento Manickathan
site_url: https://manickathan.ch/

nav:
  - Home: index.md
  - CV: cv.md
  - ... | blog/*/*
  - Projects: projects.md
  - Links:
    - tools.md
    - wiki.md


theme:
  name: material
  custom_dir: overrides
  logo: assets/logo.png
  favicon: images/favicon.svg
  font:
    text: Noto Sans
    code: Fira code
  palette:
    - scheme: default
      primary: black
      accent: light blue
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest
    - search.highlight
    - navigation.top

plugins:
  - search
  - mermaid2
  # - git-revision-date
  - macros
  - mkdocs-jupyter:
      include_source: True
  - awesome-pages

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic:
      mode: view
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - attr_list
  - md_in_html
  - meta

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lento234
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MrLento234
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lento-manickathan/
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/mrlento234
    - icon: fontawesome/solid/graduation-cap
      link: https://scholar.google.ch/citations?user=wS-b8RcAAAAJ
  analytics:
    provider: google
    property: G-SDQ15H0726

extra_javascript:
  # - js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - assets/extra.css
