site_name: Lento Manickathan
site_url: https://manickathan.ch/
copyright: Copyright &copy; 2021 - Lento Manickathan
site_url: https://lent234.github.io
site_dir: public
repo_url: https://github.com/lento234/lento234.github.io
repo_name: src

nav:
  - Home: index.md
  - CV: cv.md
  - Blog:
    - blog/arch-linux.md
    - blog/gateway.md
    - blog/h5py_parallel.md
    - blog/linear_regression.ipynb

theme:
  name: material
  logo: assets/logo.png
  favicon: images/favicon.svg
  palette:
  - scheme: default
    primary: black
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - scheme: slate
    primary: black
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
        
  features:
    - navigation.tabs

plugins:
  - search
  - git-revision-date-localized:
      type: timeago
  - macros
  - mkdocs-jupyter:
      include_source: True

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic:
      mode: view
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - def_list

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/lento234
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/MrLento234
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/lento-manickathan/
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/u/mrlento234
  analytics:
    provider: google
    property: G-SDQ15H0726

extra_javascript:
  - js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
