name: Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Test mkdocs consistancy before merging
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build test
        run: |
          git config --global user.name "Github Action"
          git config --global user.email "githubaction@gmail.com"
          mkdocs build --strict --verbose
